import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demoblaze.com/');
  await expect(page.getByRole('link', { name: 'PRODUCT STORE' })).toBeVisible();
  await page.getByRole('link', { name: 'Home (current)' }).click();
  await page.getByRole('link', { name: 'Phones' }).click();
  await expect(page.locator('#navbarExample')).toContainText('Home (current)');
  await page.getByRole('link', { name: 'Samsung galaxy s6' }).click();
  await page.getByRole('heading', { name: '$360 *includes tax' }).click();
});

/*codegen is a playwright built in tool that generates test code based on user interactions with the browser.
 The above code snippet is an example of a test generated by codegen for the website "https://demoblaze.com/"*/

 // npx playwright codegen https://demoblaze.com/ -o tests/Auto-wait/codegen-spec.ts